(() => {
  window.CONTENT = {
    monsters: {
      types: [
        { id: "grunt", labelKey: "monster.type.grunt", hpMult: 1, goldMult: 1, dodge: 0 },
        { id: "tank", labelKey: "monster.type.tank", hpMult: 2.2, goldMult: 1.6, dodge: 0 },
        { id: "runner", labelKey: "monster.type.runner", hpMult: 0.7, goldMult: 0.9, dodge: 0.08 },
      ],
    },
    regions: [
      {
        id: "greenfields",
        start: 1,
        end: 10,
        nameKey: "region.greenfields.name",
        subtitleKey: "region.greenfields.sub",
        setKey: "collection.greenfields",
        enemies: [
          "region.greenfields.enemy1",
          "region.greenfields.enemy2",
          "region.greenfields.enemy3",
          "region.greenfields.enemy4",
          "region.greenfields.enemy5",
          "region.greenfields.enemy6",
          "region.greenfields.enemy7",
          "region.greenfields.enemy8",
        ],
      },
      {
        id: "ashen-ruins",
        start: 11,
        end: 20,
        nameKey: "region.ashen.name",
        subtitleKey: "region.ashen.sub",
        setKey: "collection.ashen",
        enemies: [
          "region.ashen.enemy1",
          "region.ashen.enemy2",
          "region.ashen.enemy3",
          "region.ashen.enemy4",
          "region.ashen.enemy5",
          "region.ashen.enemy6",
          "region.ashen.enemy7",
          "region.ashen.enemy8",
        ],
      },
      {
        id: "crypt-depths",
        start: 21,
        end: 30,
        nameKey: "region.crypt.name",
        subtitleKey: "region.crypt.sub",
        setKey: "collection.crypt",
        enemies: [
          "region.crypt.enemy1",
          "region.crypt.enemy2",
          "region.crypt.enemy3",
          "region.crypt.enemy4",
          "region.crypt.enemy5",
          "region.crypt.enemy6",
          "region.crypt.enemy7",
          "region.crypt.enemy8",
        ],
      },
      {
        id: "frost-peaks",
        start: 31,
        end: 40,
        nameKey: "region.frost.name",
        subtitleKey: "region.frost.sub",
        setKey: "collection.frost",
        enemies: [
          "region.frost.enemy1",
          "region.frost.enemy2",
          "region.frost.enemy3",
          "region.frost.enemy4",
          "region.frost.enemy5",
          "region.frost.enemy6",
          "region.frost.enemy7",
          "region.frost.enemy8",
        ],
      },
      {
        id: "void-gate",
        start: 41,
        end: 50,
        nameKey: "region.void.name",
        subtitleKey: "region.void.sub",
        setKey: "collection.void",
        enemies: [
          "region.void.enemy1",
          "region.void.enemy2",
          "region.void.enemy3",
          "region.void.enemy4",
          "region.void.enemy5",
          "region.void.enemy6",
          "region.void.enemy7",
          "region.void.enemy8",
        ],
      },
    ],
    itemNames: {
      prefixes: [
        "item.prefix.old",
        "item.prefix.runed",
        "item.prefix.gleaming",
        "item.prefix.cursed",
        "item.prefix.ancient",
        "item.prefix.sturdy",
      ],
      weapons: [
        "item.weapon.blade",
        "item.weapon.axe",
        "item.weapon.spear",
        "item.weapon.hammer",
        "item.weapon.dagger",
        "item.weapon.mace",
      ],
      relics: [
        "item.relic.relic",
        "item.relic.talisman",
        "item.relic.sigil",
        "item.relic.charm",
        "item.relic.emblem",
        "item.relic.token",
      ],
    },
    affixes: {
      weapon: [
        { id: "steel", nameKey: "affix.steel", statType: "click", values: { Common: 2, Rare: 4, Epic: 6 } },
        { id: "swift", nameKey: "affix.swift", statType: "crit", values: { Common: 2, Rare: 3, Epic: 4 } },
        {
          id: "precise",
          nameKey: "affix.precise",
          statType: "critMult",
          values: { Common: 0.05, Rare: 0.1, Epic: 0.15 },
        },
        { id: "fury", nameKey: "affix.fury", statType: "click", values: { Common: 1, Rare: 3, Epic: 5 } },
      ],
      relic: [
        { id: "greedy", nameKey: "affix.greedy", statType: "gold", values: { Common: 2, Rare: 4, Epic: 6 } },
        { id: "steady", nameKey: "affix.steady", statType: "auto", values: { Common: 2, Rare: 4, Epic: 6 } },
        { id: "keen", nameKey: "affix.keen", statType: "crit", values: { Common: 2, Rare: 3, Epic: 4 } },
        { id: "steadyhand", nameKey: "affix.steadyhand", statType: "auto", values: { Common: 1, Rare: 3, Epic: 5 } },
      ],
    },
    runeEffects: [
      { id: "boss", labelKey: "rune.effect.boss" },
      { id: "greed", labelKey: "rune.effect.greed" },
      { id: "precision", labelKey: "rune.effect.precision" },
      { id: "swiftness", labelKey: "rune.effect.swiftness" },
      { id: "fury", labelKey: "rune.effect.fury" },
      { id: "tinker", labelKey: "rune.effect.tinker" },
    ],
    events: [
      { id: "gold", nameKey: "event.gold", duration: 10, goldPct: 100 },
      { id: "frenzy", nameKey: "event.frenzy", duration: 10, clickPct: 100 },
      { id: "overclock", nameKey: "event.overclock", duration: 10, autoPct: 100 },
      { id: "lucky", nameKey: "event.lucky", duration: 12, critPct: 15 },
      { id: "weakness", nameKey: "event.weakness", duration: 10, typePct: 50 },
    ],
    quests: {
      templates: [
        { id: "kill_basic", titleKey: "quest.kill_basic.title", descKey: "quest.kill_basic.desc", type: "kill", target: [25, 60], reward: { type: "gold", min: 120, max: 280 } },
        { id: "kill_bosses", titleKey: "quest.kill_bosses.title", descKey: "quest.kill_bosses.desc", type: "boss_kill", target: [2, 5], reward: { type: "gold", min: 220, max: 380 } },
        { id: "click_damage", titleKey: "quest.click_damage.title", descKey: "quest.click_damage.desc", type: "click_damage", target: [250, 900], reward: { type: "gold", min: 160, max: 320 } },
        { id: "crit_hits", titleKey: "quest.crit_hits.title", descKey: "quest.crit_hits.desc", type: "crit", target: [6, 18], reward: { type: "gold", min: 180, max: 300 } },
        { id: "earn_gold", titleKey: "quest.earn_gold.title", descKey: "quest.earn_gold.desc", type: "gold_earned", target: [300, 900], reward: { type: "gold", min: 180, max: 350 } },
        { id: "reach_zone", titleKey: "quest.reach_zone.title", descKey: "quest.reach_zone.desc", type: "zone_reach", target: [4, 8], reward: { type: "honor", min: 1, max: 1 } },
        { id: "boss_hunt", titleKey: "quest.boss_hunt.title", descKey: "quest.boss_hunt.desc", type: "boss_kill", target: [3, 6], reward: { type: "honor", min: 1, max: 1 } },
        { id: "rapid_kills", titleKey: "quest.rapid_kills.title", descKey: "quest.rapid_kills.desc", type: "kill", target: [45, 90], reward: { type: "gold", min: 250, max: 420 } },
        { id: "crit_spree", titleKey: "quest.crit_spree.title", descKey: "quest.crit_spree.desc", type: "crit", target: [12, 25], reward: { type: "gold", min: 240, max: 420 } },
        { id: "click_master", titleKey: "quest.click_master.title", descKey: "quest.click_master.desc", type: "click_damage", target: [600, 1400], reward: { type: "honor", min: 1, max: 1 } },
        { id: "rune_favor", titleKey: "quest.rune_favor.title", descKey: "quest.rune_favor.desc", type: "kill", target: [35, 70], reward: { type: "rune", min: 1, max: 1 } },
      ],
      weekly: [
        { id: "weekly_kills", titleKey: "quest.weekly_kills.title", descKey: "quest.weekly_kills.desc", type: "kill", target: [300, 500], reward: { type: "honor", min: 3, max: 3 } },
        { id: "weekly_boss", titleKey: "quest.weekly_boss.title", descKey: "quest.weekly_boss.desc", type: "boss_kill", target: [15, 25], reward: { type: "honor", min: 3, max: 3 } },
        { id: "weekly_gold", titleKey: "quest.weekly_gold.title", descKey: "quest.weekly_gold.desc", type: "gold_earned", target: [4000, 6500], reward: { type: "title", min: "title.weekly_victor", max: "title.weekly_victor" } },
      ],
      chains: [
        { id: "chain_slayer", titleKey: "quest.chain_slayer", steps: [
          { type: "kill", target: 60, descKey: "quest.chain_slayer_1" },
          { type: "boss_kill", target: 5, descKey: "quest.chain_slayer_2" },
          { type: "kill", target: 120, descKey: "quest.chain_slayer_3" },
        ]},
        { id: "chain_crit", titleKey: "quest.chain_crit", steps: [
          { type: "crit", target: 10, descKey: "quest.chain_crit_1" },
          { type: "click_damage", target: 800, descKey: "quest.chain_crit_2" },
          { type: "crit", target: 20, descKey: "quest.chain_crit_3" },
        ]},
        { id: "chain_gold", titleKey: "quest.chain_gold", steps: [
          { type: "gold_earned", target: 600, descKey: "quest.chain_gold_1" },
          { type: "gold_earned", target: 1200, descKey: "quest.chain_gold_2" },
          { type: "gold_earned", target: 2000, descKey: "quest.chain_gold_3" },
        ]},
        { id: "chain_zone", titleKey: "quest.chain_zone", steps: [
          { type: "zone_reach", target: 6, descKey: "quest.chain_zone_1" },
          { type: "zone_reach", target: 8, descKey: "quest.chain_zone_2" },
          { type: "zone_reach", target: 10, descKey: "quest.chain_zone_3" },
        ]},
        { id: "chain_master", titleKey: "quest.chain_master", steps: [
          { type: "kill", target: 80, descKey: "quest.chain_master_1" },
          { type: "click_damage", target: 1000, descKey: "quest.chain_master_2" },
          { type: "boss_kill", target: 7, descKey: "quest.chain_master_3" },
        ]},
      ],
    },
    achievements: [
      { id: "kills_100", titleKey: "ach.kills_100.title", descKey: "ach.kills_100.desc", rewardKey: "title.monster_scout", check: (s) => s.meta.lifetimeKills >= 100 },
      { id: "kills_1000", titleKey: "ach.kills_1000.title", descKey: "ach.kills_1000.desc", rewardKey: "title.grim_reaper", check: (s) => s.meta.lifetimeKills >= 1000 },
      { id: "kills_10000", titleKey: "ach.kills_10000.title", descKey: "ach.kills_10000.desc", rewardKey: "title.storm_steel", check: (s) => s.meta.lifetimeKills >= 10000 },
      { id: "boss_50", titleKey: "ach.boss_50.title", descKey: "ach.boss_50.desc", rewardKey: "title.boss_hunter", check: (s) => s.meta.lifetimeBossKills >= 50 },
      { id: "boss_200", titleKey: "ach.boss_200.title", descKey: "ach.boss_200.desc", rewardKey: "title.boss_bane", check: (s) => s.meta.lifetimeBossKills >= 200 },
      { id: "chapter_1", titleKey: "ach.chapter_1.title", descKey: "ach.chapter_1.desc", rewardKey: "title.chapter_breaker", check: (s) => s.meta.lifetimeChapterBossKills >= 1 },
      { id: "chapter_5", titleKey: "ach.chapter_5.title", descKey: "ach.chapter_5.desc", rewardKey: "title.saga_ender", check: (s) => s.meta.lifetimeChapterBossKills >= 5 },
      { id: "prestige_1", titleKey: "ach.prestige_1.title", descKey: "ach.prestige_1.desc", rewardKey: "title.ascended", check: (s) => s.meta.lifetimePrestiges >= 1 },
      { id: "prestige_5", titleKey: "ach.prestige_5.title", descKey: "ach.prestige_5.desc", rewardKey: "title.reborn_veteran", check: (s) => s.meta.lifetimePrestiges >= 5 },
      { id: "honor_10", titleKey: "ach.honor_10.title", descKey: "ach.honor_10.desc", rewardKey: "title.honored", check: (s) => s.meta.totalHonor >= 10 },
      { id: "honor_50", titleKey: "ach.honor_50.title", descKey: "ach.honor_50.desc", rewardKey: "title.noble", check: (s) => s.meta.totalHonor >= 50 },
      { id: "rare_weapon", titleKey: "ach.rare_weapon.title", descKey: "ach.rare_weapon.desc", rewardKey: "title.arsenal", check: (s) => s.meta.foundRareWeapon },
      { id: "epic_weapon", titleKey: "ach.epic_weapon.title", descKey: "ach.epic_weapon.desc", rewardKey: "title.master_forge", check: (s) => s.meta.foundEpicWeapon },
      { id: "rare_relic", titleKey: "ach.rare_relic.title", descKey: "ach.rare_relic.desc", rewardKey: "title.relic_seeker", check: (s) => s.meta.foundRareRelic },
      { id: "epic_relic", titleKey: "ach.epic_relic.title", descKey: "ach.epic_relic.desc", rewardKey: "title.artifact_hunter", check: (s) => s.meta.foundEpicRelic },
      { id: "rare_rune", titleKey: "ach.rare_rune.title", descKey: "ach.rare_rune.desc", rewardKey: "title.rune_collector", check: (s) => s.meta.foundRareRune },
      { id: "epic_rune", titleKey: "ach.epic_rune.title", descKey: "ach.epic_rune.desc", rewardKey: "title.rune_sage", check: (s) => s.meta.foundEpicRune },
      { id: "quests_10", titleKey: "ach.quests_10.title", descKey: "ach.quests_10.desc", rewardKey: "title.taskmaster", check: (s) => s.meta.lifetimeQuestClaims >= 10 },
      { id: "quests_50", titleKey: "ach.quests_50.title", descKey: "ach.quests_50.desc", rewardKey: "title.quest_lord", check: (s) => s.meta.lifetimeQuestClaims >= 50 },
      { id: "region_ruins", titleKey: "ach.region_ruins.title", descKey: "ach.region_ruins.desc", rewardKey: "title.ash_walker", check: (s) => s.meta.regionsReached.includes("ashen-ruins") },
      { id: "region_crypt", titleKey: "ach.region_crypt.title", descKey: "ach.region_crypt.desc", rewardKey: "title.crypt_delver", check: (s) => s.meta.regionsReached.includes("crypt-depths") },
      { id: "region_void", titleKey: "ach.region_void.title", descKey: "ach.region_void.desc", rewardKey: "title.void_touched", check: (s) => s.meta.regionsReached.includes("void-gate") },
      { id: "skills_50", titleKey: "ach.skills_50.title", descKey: "ach.skills_50.desc", rewardKey: "title.commander", check: (s) => s.meta.lifetimeSkillUses >= 50 },
      { id: "skills_200", titleKey: "ach.skills_200.title", descKey: "ach.skills_200.desc", rewardKey: "title.tactician", check: (s) => s.meta.lifetimeSkillUses >= 200 },
    ],
  };

  window.I18N = {
    en: {
      tabs: {
        shop: "Shop",
        inventory: "Inventory",
        runes: "Runes",
        mercs: "Mercenaries",
        quests: "Quests",
        achievements: "Achievements",
        collections: "Collections",
        settings: "Settings",
        log: "Log",
      },
      ui: {
        gold: "Gold",
        honor: "Honor",
        dmgMult: "DMG Mult",
        zone: "Zone",
        kills: "Kills",
        title: "Title",
        boss: "Boss",
        chapterBoss: "CHAPTER BOSS",
        clickHint: "Click the monster to attack",
        clickDamage: "Click Damage",
        autoDps: "Auto DPS",
        critChance: "Crit Chance",
        critMult: "Crit Multiplier",
        goldBonus: "Gold Bonus",
        zoneProgress: "Zone Progress",
        upgrades: "Upgrades",
        level: "Level",
        buy: "Buy",
        max: "Max",
        chapter: "Chapter",
        activate: "Activate",
        skillPower: "Power Strike",
        skillCry: "Battle Cry",
        sfx: "SFX",
        sfxVolume: "SFX Volume",
        event: "Event",
        monsterHp: "Monster HP",
        monsterType: "Monster Type",
        mercHire: "Mercenary Hire",
        mercHireBtn: "Hire (1 Honor)",
        mercFreeHire: "1 Free Hire",
        mercOdds: "Odds: F 55% / E 28% / D 12% / C 4% / B 1%",
        mercSlots: "Equipped Slots",
        mercAddSlot: "Add Slot",
        mercRoster: "Owned Roster",
        mercSelected: "Selected: {name} Lv.{level}",
        mercEmpty: "Empty",
        mercLevelCost: "Level Cost",
        mercClass: "Class",
        mercGrade: "Grade",
        mercLevel: "Level",
        mercBasic: "Basic",
        mercBasicShort: "HIT",
        mercBasicHit: "Basic Hit",
        mercBasicDps: "Basic DPS",
        mercInterval: "Interval",
        mercSkill: "Skill",
        mercCooldown: "Cooldown",
        mercDuration: "Duration",
        mercBossBonus: "Boss Bonus",
        mercBasicLabel: "Basic",
        mercDps: "DPS",
        weaponSlot: "Weapon Slot",
        relicSlot: "Relic Slot",
        inventory: "Inventory",
        inventorySlots: "Slots: {count}/{max}",
        expandInventory: "Expand (+1) {cost}g",
        unequip: "Unequip",
        manageRunes: "Manage Runes",
        removeRune: "Remove Rune",
        runeShop: "Rune Shop",
        runePouch: "Rune Pouch",
        weekly: "Weekly Quest",
        chain: "Quest Chain",
        regularQuests: "Regular Quests",
        reroll: "Reroll",
        all: "All",
        unlocked: "Unlocked",
        locked: "Locked",
        equipTitle: "Equip Title",
        session: "Session",
        save: "Save",
        reset: "Reset",
        prestige: "Prestige",
        refresh: "Refresh",
        refreshFree: "Refresh (Free)",
        refreshCost: "Refresh ({cost}g)",
        reward: "Reward",
        claim: "Claim",
        inProgress: "In Progress",
        equip: "Equip",
        equipped: "Equipped",
        socket: "Socket",
        socketed: "Socketed",
        bossAlert: "BOSS!",
        victory: "VICTORY",
        equipRelicFirst: "Equip a relic first.",
        nextChapter: "Next Chapter Boss: Zone {zone}",
        weeklyReset: "Weekly resets in {days}d",
        none: "None",
        empty: "Empty",
        socketedStatus: "Socketed: {name}",
        socketedNone: "Socketed: None",
        noBonus: "No bonus",
        rune: "Rune",
        weapon: "Weapon",
        relic: "Relic",
        affix: "Affix",
        needRelicRune: "Equip a relic to socket a rune.",
        noRune: "No rune socketed.",
        miss: "MISS",
        skillActive: "Active {time}",
        skillCooldown: "Cooldown {time}",
        skillReady: "Ready",
        skillCdr: "Skill CDR",
        confirmPrestige: "Prestige and reset your run?",
        confirmReset: "Reset all progress and clear save?",
        confirmImport: "Import this save and overwrite current data?",
        confirmReplaceRune: "Replace the socketed rune?",
        offlineGain: "While you were away: +{gold} gold, +{kills} kills.",
        sessionStart: "Start",
        sessionEnd: "End",
        active: "Active",
        drops: "Drops",
        quests: "Quests",
        currentSession: "Current Session",
        lastSession: "Last Session",
        onCooldown: "Skill is on cooldown.",
        found: "Found",
        combo: "Combo: {count} (+{bonus}%)",
        setsCompleted: "Sets completed: {count}/5",
        collectionBonus: "Collection bonus: +{bonus}% gold",
        metaBonuses: "Meta Bonuses",
        refreshDiscount: "Shop Refresh",
        runeRareBonus: "Rune Rare Chance",
        sellBonus: "Sell Value",
        chapterRewardTitle: "Chapter Reward",
        chapterRewardSub: "Choose one permanent bonus",
        bossPattern: "Boss Pattern",
        guard: "GUARD",
        evasion: "EVADE 20%",
        enrage: "ENRAGED",
        errors: "Errors",
        rarity: "Rarity",
        effect: "Effect",
        type: "Type",
        set: "Set",
        glyphWeapon: "W",
        glyphRelic: "R",
        welcomeBack: "Welcome Back",
        continue: "Continue",
        sessionReport: "Session Report",
        exportImport: "Export / Import Save",
        copy: "Copy",
        close: "Close",
        devPanel: "Dev Panel",
        devGold: "Give +10,000 gold",
        devZone: "Advance Zone +1",
        devBoss: "Spawn Boss",
        export: "Export",
        import: "Import",
        runTests: "Run UI Tests",
        clickCheckOn: "Click Check: On",
        clickCheckOff: "Click Check: Off",
        testsTitle: "UI Tests",
        testsPassed: "passed",
        testsFailed: "failed",
        testsPass: "PASS",
        testsFail: "FAIL",
        testsMissing: "Missing",
        testsDisabled: "Disabled",
        testsError: "Error",
      },
      btn: {
        equip: "Equip",
        unequip: "Unequip",
        sell: "Sell",
        socket: "Socket",
        unsocket: "Unsocket",
      },
      confirm: {
        sellItem: "Sell {name} for {gold} gold?",
        sellRune: "Sell {name} for {gold} gold?",
        replaceSocket: "Replace the socketed rune?",
      },
      msg: {
        soldItem: "Sold: {name} (+{gold}G).",
        soldRune: "Sold: {name} (+{gold}G).",
        cannotSellEquipped: "Unequip the item before selling.",
        cannotSellSocketed: "Unsocket the rune before selling.",
      },
      settings: {
        language: "Language",
        numberFormat: "Number Format",
        reduceFx: "Reduce Effects",
        sfx: "SFX",
        sfxVolume: "SFX Volume",
        compact: "Compact UI",
        devMode: "Dev Mode",
        showLogTab: "Show Log Tab",
        full: "Full",
        abbr: "Abbrev",
        on: "On",
        off: "Off",
      },
      runes: {
        shop: {
          selectOffer: "Select shop rune",
          purchase: "Buy",
          noSelection: "No selection",
          cannotAfford: "Not enough gold",
        },
        socket: {
          reason: {
            noRuneSelected: "Select a rune",
            noRelicEquipped: "Equip a relic first",
            alreadySocketed: "Rune already socketed",
          },
        },
      },
      upgrades: {
        sword: { title: "Sword Training", desc: "+1 click damage" },
        merc: { title: "Auto Combat Training", desc: "+1 auto DPS" },
        edge: { title: "Sharpened Edge", desc: "+2% crit chance (cap 50%)" },
        swing: { title: "Heavy Swing", desc: "+0.1 crit multiplier (cap 3.0x)" },
      },
      merc: {
        grade: {
          f: "F",
          e: "E",
          d: "D",
          c: "C",
          b: "B",
        },
        class: {
          striker: "Striker",
          rapid: "Rapid",
          support: "Support",
          breaker: "Breaker",
        },
        skill: {
          striker: "Strike",
          rapid: "Rapid Attack",
          support: "Battle Chant",
          breaker: "Breaker",
        },
      },
      skill: {
        powerDesc: "Click damage x3 for 4s",
        cryDesc: "Auto DPS x2 +20% gold for 6s",
      },
      region: {
        greenfields: {
          name: "Greenfields",
          sub: "Breezy fields and soft hills",
          enemy1: "Wandering Slime",
          enemy2: "Meadow Imp",
          enemy3: "Twig Sprout",
          enemy4: "Rustling Boar",
          enemy5: "Thornling",
          enemy6: "Moss Beetle",
          enemy7: "Bramble Rat",
          enemy8: "Hollow Crow",
        },
        ashen: {
          name: "Ashen Ruins",
          sub: "Broken stone and ember dust",
          enemy1: "Cinder Wight",
          enemy2: "Ashling",
          enemy3: "Rubble Troll",
          enemy4: "Smolder Bat",
          enemy5: "Coal Wisp",
          enemy6: "Ruins Bandit",
          enemy7: "Scorchling",
          enemy8: "Burnt Golem",
        },
        crypt: {
          name: "Crypt Depths",
          sub: "Cold echoes and ancient bones",
          enemy1: "Graveling",
          enemy2: "Bone Skulker",
          enemy3: "Crypt Moth",
          enemy4: "Ghoul Pike",
          enemy5: "Mire Spirit",
          enemy6: "Rot Hound",
          enemy7: "Dust Lich",
          enemy8: "Tomb Guard",
        },
        frost: {
          name: "Frost Peaks",
          sub: "Wind-cut ice and biting chill",
          enemy1: "Ice Gnarl",
          enemy2: "Frost Hare",
          enemy3: "Glacier Whelp",
          enemy4: "Snow Stalker",
          enemy5: "Rime Boar",
          enemy6: "Peak Ravager",
          enemy7: "Shiver Drake",
          enemy8: "Hoarfang",
        },
        void: {
          name: "Void Gate",
          sub: "Whispering dark beyond the veil",
          enemy1: "Voidling",
          enemy2: "Warped Knight",
          enemy3: "Shade Weaver",
          enemy4: "Abyss Echo",
          enemy5: "Night Marauder",
          enemy6: "Null Seraph",
          enemy7: "Grim Oracle",
          enemy8: "Gate Sentinel",
        },
      },
      collection: {
        greenfields: "Greenfields Set",
        ashen: "Ashen Set",
        crypt: "Crypt Set",
        frost: "Frost Set",
        void: "Void Set",
        completed: "Discovered",
        missing: "Missing",
      },
      monster: {
        type: { grunt: "Grunt", tank: "Tank", runner: "Runner" },
      },
      rarity: { common: "Common", rare: "Rare", epic: "Epic" },
      rune: {
        effect: {
          boss: "Boss Slayer",
          greed: "Greed",
          precision: "Precision",
          swiftness: "Swiftness",
          fury: "Fury",
          tinker: "Tinker",
        },
        glyph: {
          boss: "B",
          greed: "G",
          precision: "P",
          swiftness: "S",
          fury: "F",
          tinker: "T",
        },
      },
      item: {
        prefix: {
          old: "Old",
          runed: "Runed",
          gleaming: "Gleaming",
          cursed: "Cursed",
          ancient: "Ancient",
          sturdy: "Sturdy",
        },
        weapon: {
          blade: "Blade",
          axe: "Axe",
          spear: "Spear",
          hammer: "Hammer",
          dagger: "Dagger",
          mace: "Mace",
        },
        relic: {
          relic: "Relic",
          talisman: "Talisman",
          sigil: "Sigil",
          charm: "Charm",
          emblem: "Emblem",
          token: "Token",
        },
      },
      affix: {
        steel: "Steel",
        swift: "Swift",
        precise: "Precise",
        fury: "Fury",
        greedy: "Greedy",
        steady: "Steady",
        keen: "Keen",
        steadyhand: "Steadyhand",
      },
      event: {
        gold: "Gold Rush",
        frenzy: "Frenzy",
        overclock: "Overclock",
        lucky: "Lucky Crits",
        weakness: "Weakness Exposed",
      },
      quest: {
        kill_basic: { title: "Cull the Wilds", desc: "Defeat {target} monsters" },
        kill_bosses: { title: "Break the Siege", desc: "Defeat {target} bosses" },
        click_damage: { title: "Sharpen Your Strikes", desc: "Deal {target} click damage" },
        crit_hits: { title: "Lucky Blows", desc: "Land {target} critical hits" },
        earn_gold: { title: "Pouch Filler", desc: "Earn {target} gold" },
        reach_zone: { title: "Scout the Frontier", desc: "Reach zone {target}" },
        boss_hunt: { title: "Warlord Bounty", desc: "Defeat {target} bosses" },
        rapid_kills: { title: "Fast Hands", desc: "Defeat {target} monsters" },
        crit_spree: { title: "Edge of Fate", desc: "Trigger {target} critical hits" },
        click_master: { title: "Hammer Time", desc: "Deal {target} click damage" },
        rune_favor: { title: "Rune Favor", desc: "Defeat {target} monsters" },
        weekly_kills: { title: "Weekly Hunt", desc: "Defeat {target} monsters" },
        weekly_boss: { title: "Weekly Siege", desc: "Defeat {target} bosses" },
        weekly_gold: { title: "Weekly Fortune", desc: "Earn {target} gold" },
        chain_slayer: "Slayer Path",
        chain_slayer_1: "Defeat 60 monsters",
        chain_slayer_2: "Defeat 5 bosses",
        chain_slayer_3: "Defeat 120 monsters",
        chain_crit: "Critical Path",
        chain_crit_1: "Land 10 critical hits",
        chain_crit_2: "Deal 800 click damage",
        chain_crit_3: "Land 20 critical hits",
        chain_gold: "Golden Path",
        chain_gold_1: "Earn 600 gold",
        chain_gold_2: "Earn 1,200 gold",
        chain_gold_3: "Earn 2,000 gold",
        chain_zone: "Frontier Path",
        chain_zone_1: "Reach zone 6",
        chain_zone_2: "Reach zone 8",
        chain_zone_3: "Reach zone 10",
        chain_master: "Master Path",
        chain_master_1: "Defeat 80 monsters",
        chain_master_2: "Deal 1,000 click damage",
        chain_master_3: "Defeat 7 bosses",
      },
      ach: {
        kills_100: { title: "First Blood", desc: "Defeat 100 monsters" },
        kills_1000: { title: "Grim Reaper", desc: "Defeat 1,000 monsters" },
        kills_10000: { title: "Storm of Steel", desc: "Defeat 10,000 monsters" },
        boss_50: { title: "Boss Hunter", desc: "Defeat 50 bosses" },
        boss_200: { title: "Boss Bane", desc: "Defeat 200 bosses" },
        chapter_1: { title: "Chapter Breaker", desc: "Defeat 1 chapter boss" },
        chapter_5: { title: "Saga Ender", desc: "Defeat 5 chapter bosses" },
        prestige_1: { title: "Ascended", desc: "Prestige once" },
        prestige_5: { title: "Reborn Veteran", desc: "Prestige 5 times" },
        honor_10: { title: "Honored", desc: "Earn 10 Honor" },
        honor_50: { title: "Noble", desc: "Earn 50 Honor" },
        rare_weapon: { title: "Arsenal", desc: "Obtain a Rare weapon" },
        epic_weapon: { title: "Master Forge", desc: "Obtain an Epic weapon" },
        rare_relic: { title: "Rare Find", desc: "Obtain a Rare relic" },
        epic_relic: { title: "Epic Find", desc: "Obtain an Epic relic" },
        rare_rune: { title: "Rune Collector", desc: "Obtain a Rare rune" },
        epic_rune: { title: "Rune Sage", desc: "Obtain an Epic rune" },
        quests_10: { title: "Taskmaster", desc: "Complete 10 quests" },
        quests_50: { title: "Quest Lord", desc: "Complete 50 quests" },
        region_ruins: { title: "Ash Walker", desc: "Enter Ashen Ruins" },
        region_crypt: { title: "Crypt Delver", desc: "Enter Crypt Depths" },
        region_void: { title: "Void Touched", desc: "Enter Void Gate" },
        skills_50: { title: "Commander", desc: "Use a skill 50 times" },
        skills_200: { title: "Tactician", desc: "Use a skill 200 times" },
      },
      title: {
        monster_scout: "Monster Scout",
        grim_reaper: "Grim Reaper",
        storm_steel: "Storm of Steel",
        boss_hunter: "Boss Hunter",
        boss_bane: "Boss Bane",
        chapter_breaker: "Chapter Breaker",
        saga_ender: "Saga Ender",
        ascended: "Ascended",
        reborn_veteran: "Reborn Veteran",
        honored: "Honored",
        noble: "Noble",
        arsenal: "Arsenal",
        master_forge: "Master Forge",
        relic_seeker: "Relic Seeker",
        artifact_hunter: "Artifact Hunter",
        rune_collector: "Rune Collector",
        rune_sage: "Rune Sage",
        taskmaster: "Taskmaster",
        quest_lord: "Quest Lord",
        ash_walker: "Ash Walker",
        crypt_delver: "Crypt Delver",
        void_touched: "Void Touched",
        commander: "Commander",
        tactician: "Tactician",
        collector: "Collector",
        weekly_victor: "Weekly Victor",
      },
      log: {
        notEnoughGold: "Not enough gold.",
        upgradeBought: "Bought: {name} x{count} (-{gold}G).",
        boughtRune: "Bought Rune: {name}.",
        equippedWeapon: "Equipped Weapon: {name}.",
        equippedRelic: "Equipped Relic: {name}.",
        unequipWeapon: "Weapon unequipped.",
        unequipRelic: "Relic unequipped.",
        actionBlocked: "Action blocked: {action}.",
        socketedRune: "Socketed rune: {name}.",
        removedRune: "Rune removed: {name}.",
        relicRequired: "Equip a relic first.",
        claimQuest: "Claimed Quest: {title} ({reward}).",
        questRewardRune: "Quest reward: {name}.",
        questComplete: "Quest complete: {title}",
        weeklyComplete: "Weekly quest complete: {title}",
        chainComplete: "Quest chain completed!",
        eventStart: "Event started: {name}",
        chapterDefeat: "Chapter boss defeated!",
        regionReached: "Region reached: {name}",
        inventoryFull: "Inventory full. Gear discarded.",
        inventoryExpand: "Inventory expanded: {max} slots.",
        runeFull: "Rune pouch full. Rune discarded.",
        shopRefresh: "Rune shop refreshed.",
        prestige: "Prestiged for {amount} Honor.",
        weakHit: "Weak point hit!",
        runnerDodge: "The runner dodged your strike.",
        achievement: "Achievement unlocked: {title}",
        importFail: "Import failed: invalid JSON.",
        saveCopied: "Save data copied.",
        clickBlocked: "CLICK BLOCKED by {target}",
        actionError: "Action error. Check console.",
        mercHired: "Hired: {name}.",
        mercEquipped: "Equipped: {name}.",
        mercUnequipped: "Unequipped: {name}.",
        mercLeveled: "Leveled: {name} +{count} (-{gold}G).",
        mercSlotUnlocked: "Merc slot unlocked.",
      },
      reward: {
        greedTitle: "Greed",
        greedDesc: "+3% gold gain",
        slayerTitle: "Slayer",
        slayerDesc: "+5% boss damage",
        focusTitle: "Focus",
        focusDesc: "-3% skill cooldown",
        sparkTitle: "Spark",
        sparkDesc: "+2% click damage",
        engineTitle: "Engine",
        engineDesc: "+2% auto DPS",
        refreshTitle: "Frugal",
        refreshDesc: "-10% shop refresh cost",
        runeRareTitle: "Arcane",
        runeRareDesc: "+2% rune rare chance",
        sellTitle: "Broker",
        sellDesc: "+10% sell value",
      },
      boss: {
        guardDesc: "Guard for 2.5s every 6s (click damage -50%).",
        evasionDesc: "Boss dodges 20% of clicks.",
        enrageDesc: "At 30% HP, takes +15% damage.",
      },
      tutorial: {
        title: "Tutorial",
        step1: "Click the monster 5 times.",
        step2: "Buy Sword Training once.",
        step3: "Buy Auto Combat Training once.",
        step4: "Use your active skill once.",
        step5: "Open Runes tab and buy a rune.",
        moreGold: "Defeat more monsters to afford a rune.",
        next: "Next",
        skip: "Skip",
      },
    },
    ko: {
      tabs: {
        shop: "상점",
        inventory: "인벤토리",
        runes: "룬",
        mercs: "용병",
        quests: "퀘스트",
        achievements: "업적",
        collections: "컬렉션",
        settings: "설정",
        log: "로그",
      },
      ui: {
        gold: "골드",
        honor: "명예",
        dmgMult: "피해 배수",
        zone: "지역",
        kills: "처치",
        title: "칭호",
        boss: "보스",
        chapterBoss: "챕터 보스",
        clickHint: "몬스터를 클릭해 공격하세요",
        clickDamage: "클릭 피해",
        autoDps: "자동 DPS",
        critChance: "치명타 확률",
        critMult: "치명타 배수",
        goldBonus: "골드 보너스",
        zoneProgress: "지역 진행",
        upgrades: "강화",
        level: "레벨",
        buy: "구매",
        max: "최대",
        chapter: "챕터",
        activate: "발동",
        skillPower: "파워 스트라이크",
        skillCry: "배틀 크라이",
        sfx: "효과음",
        sfxVolume: "효과음 볼륨",
        mercHire: "용병 고용",
        mercHireBtn: "고용 (명예 1)",
        mercFreeHire: "무료 고용 1회",
        mercOdds: "확률: F 55% / E 28% / D 12% / C 4% / B 1%",
        mercSlots: "장착 슬롯",
        mercAddSlot: "슬롯 추가",
        mercRoster: "보유 목록",
        mercSelected: "선택: {name} Lv.{level}",
        mercEmpty: "비어있음",
        mercLevelCost: "강화 비용",
        mercClass: "직업",
        mercGrade: "등급",
        mercLevel: "레벨",
        mercBasic: "기본 공격",
        mercBasicShort: "기본",
        mercBasicHit: "기본 공격(1회)",
        mercBasicDps: "기본 DPS",
        mercInterval: "공격 주기",
        mercSkill: "스킬",
        mercCooldown: "쿨다운",
        mercDuration: "지속시간",
        mercBossBonus: "보스 추가 피해",
        mercBasicLabel: "기본",
        mercDps: "DPS",
        weaponSlot: "무기 슬롯",
        relicSlot: "유물 슬롯",
        inventory: "인벤토리",
        inventorySlots: "슬롯: {count}/{max}",
        expandInventory: "인벤 확장 (+1) {cost}골드",
        unequip: "해제",
        manageRunes: "룬 관리",
        removeRune: "룬 제거",
        runeShop: "룬 상점",
        runePouch: "룬 보관함",
        weekly: "주간 퀘스트",
        chain: "연쇄 퀘스트",
        regularQuests: "일반 퀘스트",
        reroll: "리롤",
        all: "전체",
        unlocked: "해금",
        locked: "잠김",
        equipTitle: "칭호 장착",
        session: "세션",
        save: "저장",
        reset: "리셋",
        prestige: "전직",
        refresh: "새로고침",
        refreshFree: "새로고침 (무료)",
        refreshCost: "새로고침 ({cost}골드)",
        reward: "보상",
        claim: "받기",
        inProgress: "진행 중",
        equip: "장착",
        equipped: "장착됨",
        socket: "장착",
        socketed: "장착됨",
        bossAlert: "보스!",
        victory: "승리",
        equipRelicFirst: "유물을 먼저 장착하세요.",
        nextChapter: "다음 챕터 보스: 지역 {zone}",
        weeklyReset: "주간 리셋 {days}일 남음",
        none: "없음",
        empty: "비어있음",
        socketedStatus: "현재 소켓: {name}",
        socketedNone: "현재 소켓: 없음",
        noBonus: "보너스 없음",
        rune: "룬",
        weapon: "무기",
        relic: "유물",
        affix: "옵션",
        needRelicRune: "유물을 장착해야 룬을 꽂을 수 있습니다.",
        noRune: "장착된 룬 없음",
        miss: "빗나감",
        skillActive: "활성 {time}",
        skillCooldown: "재사용 대기 {time}",
        skillReady: "준비 완료",
        skillCdr: "스킬 쿨감",
        confirmPrestige: "전직 후 진행이 초기화됩니다. 계속할까요?",
        confirmReset: "모든 진행을 초기화할까요?",
        confirmImport: "가져온 저장 데이터를 적용할까요?",
        confirmReplaceRune: "장착된 룬을 교체할까요?",
        offlineGain: "접속하지 않은 동안 +{gold} 골드, +{kills} 처치.",
        sessionStart: "시작",
        sessionEnd: "종료",
        active: "진행 중",
        drops: "드랍",
        quests: "퀘스트",
        currentSession: "현재 세션",
        lastSession: "이전 세션",
        onCooldown: "스킬이 재사용 대기 중입니다.",
        found: "획득",
        combo: "콤보: {count} (+{bonus}%)",
        setsCompleted: "세트 완료: {count}/5",
        collectionBonus: "컬렉션 보너스: +{bonus}% 골드",
        metaBonuses: "메타 보너스",
        refreshDiscount: "상점 새로고침",
        runeRareBonus: "룬 희귀 확률",
        sellBonus: "판매 보너스",
        chapterRewardTitle: "챕터 보상",
        chapterRewardSub: "영구 보너스 1개를 선택하세요",
        bossPattern: "보스 패턴",
        guard: "방어 태세",
        evasion: "회피 20%",
        enrage: "격노",
        errors: "오류",
        rarity: "등급",
        effect: "효과",
        type: "종류",
        set: "세트",
        glyphWeapon: "검",
        glyphRelic: "유",
        welcomeBack: "돌아오셨군요",
        continue: "계속",
        sessionReport: "세션 리포트",
        exportImport: "저장 내보내기/가져오기",
        copy: "복사",
        close: "닫기",
        devPanel: "개발자 패널",
        devGold: "+10,000 골드",
        devZone: "지역 +1",
        devBoss: "보스 생성",
        export: "내보내기",
        import: "가져오기",
        runTests: "UI 테스트",
        clickCheckOn: "클릭 확인: 켬",
        clickCheckOff: "클릭 확인: 끔",
        testsTitle: "UI 테스트",
        testsPassed: "통과",
        testsFailed: "실패",
        testsPass: "통과",
        testsFail: "실패",
        testsMissing: "누락",
        testsDisabled: "비활성",
        testsError: "오류",
        event: "이벤트",
        monsterHp: "몬스터 HP",
        monsterType: "몬스터 타입",
      },
      btn: {
        equip: "장착",
        unequip: "해제",
        sell: "판매",
        socket: "소켓",
        unsocket: "소켓 해제",
      },
      confirm: {
        sellItem: "{name}을(를) {gold} 골드에 판매할까요?",
        sellRune: "{name}을(를) {gold} 골드에 판매할까요?",
        replaceSocket: "장착된 룬을 교체할까요?",
      },
      msg: {
        soldItem: "판매: {name} (+{gold}G).",
        soldRune: "판매: {name} (+{gold}G).",
        cannotSellEquipped: "장착 중인 아이템은 판매할 수 없습니다.",
        cannotSellSocketed: "소켓된 룬은 판매할 수 없습니다.",
      },
      settings: {
        language: "언어",
        numberFormat: "숫자 형식",
        reduceFx: "효과 줄이기",
        sfx: "효과음",
        sfxVolume: "효과음 볼륨",
        compact: "컴팩트 UI",
        devMode: "개발자 모드",
        showLogTab: "로그 탭 표시",
        full: "전체",
        abbr: "축약",
        on: "켜기",
        off: "끄기",
      },
      runes: {
        shop: {
          selectOffer: "상점 룬 선택",
          purchase: "구매",
          noSelection: "선택 없음",
          cannotAfford: "골드 부족",
        },
        socket: {
          reason: {
            noRuneSelected: "룬을 선택하세요",
            noRelicEquipped: "유물을 먼저 장착하세요",
            alreadySocketed: "이미 소켓된 룬입니다",
          },
        },
      },
      upgrades: {
        sword: { title: "검술 훈련", desc: "+1 클릭 피해" },
        merc: { title: "자동 전투 훈련", desc: "+1 자동 DPS" },
        edge: { title: "날카로운 칼날", desc: "+2% 치명타 확률(최대 50%)" },
        swing: { title: "강한 휘두르기", desc: "+0.1 치명타 배수(최대 3.0x)" },
      },
      merc: {
        grade: {
          f: "F",
          e: "E",
          d: "D",
          c: "C",
          b: "B",
        },
        class: {
          striker: "스트라이커",
          rapid: "래피드",
          support: "서포트",
          breaker: "브레이커",
        },
        skill: {
          striker: "강타",
          rapid: "연타",
          support: "전투 함성",
          breaker: "파쇄",
        },
      },
      skill: {
        powerDesc: "4초간 클릭 피해 x3",
        cryDesc: "6초간 자동 DPS x2 +20% 골드",
      },
      region: {
        greenfields: {
          name: "그린필드",
          sub: "바람 부는 들판",
          enemy1: "떠도는 슬라임",
          enemy2: "들판 임프",
          enemy3: "나뭇가지 새싹",
          enemy4: "풀숲 멧돼지",
          enemy5: "가시 괴물",
          enemy6: "이끼 딱정벌레",
          enemy7: "덩굴 쥐",
          enemy8: "속빈 까마귀",
        },
        ashen: {
          name: "잿더미 폐허",
          sub: "타버린 돌더미",
          enemy1: "재의 망령",
          enemy2: "잿불 정령",
          enemy3: "잔해 트롤",
          enemy4: "연기 박쥐",
          enemy5: "숯 위스프",
          enemy6: "폐허 도적",
          enemy7: "그을음 요정",
          enemy8: "불탄 골렘",
        },
        crypt: {
          name: "지하 묘지",
          sub: "차가운 메아리",
          enemy1: "자갈 소환수",
          enemy2: "뼈 잠복자",
          enemy3: "묘지 나방",
          enemy4: "구울 창병",
          enemy5: "늪 영혼",
          enemy6: "부패한 사냥개",
          enemy7: "먼지 리치",
          enemy8: "무덤 수호자",
        },
        frost: {
          name: "서리 봉우리",
          sub: "칼바람의 산",
          enemy1: "얼음 그늘",
          enemy2: "서리 토끼",
          enemy3: "빙하 새끼",
          enemy4: "눈 추적자",
          enemy5: "서리 멧돼지",
          enemy6: "봉우리 약탈자",
          enemy7: "빙결 드레이크",
          enemy8: "서리 송곳니",
        },
        void: {
          name: "공허의 문",
          sub: "속삭이는 심연",
          enemy1: "공허 요정",
          enemy2: "왜곡 기사",
          enemy3: "그림자 직조자",
          enemy4: "심연 메아리",
          enemy5: "밤의 약탈자",
          enemy6: "무(無) 세라프",
          enemy7: "음울한 예언자",
          enemy8: "문 수호자",
        },
      },
      collection: {
        greenfields: "그린필드 세트",
        ashen: "잿더미 세트",
        crypt: "묘지 세트",
        frost: "서리 세트",
        void: "공허 세트",
        completed: "발견됨",
        missing: "미발견",
      },
      monster: {
        type: { grunt: "일반", tank: "탱커", runner: "돌격" },
      },
      rarity: { common: "일반", rare: "희귀", epic: "영웅" },
      rune: {
        effect: {
          boss: "보스 학살",
          greed: "탐욕",
          precision: "정밀",
          swiftness: "민첩",
          fury: "격노",
          tinker: "기계공",
        },
        glyph: {
          boss: "B",
          greed: "G",
          precision: "P",
          swiftness: "S",
          fury: "F",
          tinker: "T",
        },
      },
      item: {
        prefix: {
          old: "낡은",
          runed: "룬 새긴",
          gleaming: "빛나는",
          cursed: "저주받은",
          ancient: "고대",
          sturdy: "튼튼한",
        },
        weapon: {
          blade: "검",
          axe: "도끼",
          spear: "창",
          hammer: "망치",
          dagger: "단검",
          mace: "철퇴",
        },
        relic: {
          relic: "유물",
          talisman: "부적",
          sigil: "인장",
          charm: "참",
          emblem: "문장",
          token: "토큰",
        },
      },
      affix: {
        steel: "강철의",
        swift: "신속한",
        precise: "정밀한",
        fury: "분노의",
        greedy: "탐욕의",
        steady: "안정된",
        keen: "예리한",
        steadyhand: "숙련된",
      },
      event: {
        gold: "골드 러시",
        frenzy: "광분",
        overclock: "오버클럭",
        lucky: "행운의 치명타",
        weakness: "약점 노출",
      },
      quest: {
        kill_basic: { title: "야생 처치", desc: "몬스터 {target}마리 처치" },
        kill_bosses: { title: "공성 돌파", desc: "보스 {target}마리 처치" },
        click_damage: { title: "날카로운 일격", desc: "클릭 피해 {target}" },
        crit_hits: { title: "행운의 일격", desc: "치명타 {target}회" },
        earn_gold: { title: "주머니 채우기", desc: "골드 {target} 획득" },
        reach_zone: { title: "정찰", desc: "지역 {target} 도달" },
        boss_hunt: { title: "현상금", desc: "보스 {target}마리 처치" },
        rapid_kills: { title: "빠른 손", desc: "몬스터 {target}마리 처치" },
        crit_spree: { title: "날카로운 운명", desc: "치명타 {target}회" },
        click_master: { title: "망치 시간", desc: "클릭 피해 {target}" },
        rune_favor: { title: "룬의 축복", desc: "몬스터 {target}마리 처치" },
        weekly_kills: { title: "주간 사냥", desc: "몬스터 {target}마리 처치" },
        weekly_boss: { title: "주간 공성", desc: "보스 {target}마리 처치" },
        weekly_gold: { title: "주간 행운", desc: "골드 {target} 획득" },
        chain_slayer: "사냥꾼의 길",
        chain_slayer_1: "몬스터 60마리 처치",
        chain_slayer_2: "보스 5마리 처치",
        chain_slayer_3: "몬스터 120마리 처치",
        chain_crit: "치명타의 길",
        chain_crit_1: "치명타 10회",
        chain_crit_2: "클릭 피해 800",
        chain_crit_3: "치명타 20회",
        chain_gold: "황금의 길",
        chain_gold_1: "골드 600 획득",
        chain_gold_2: "골드 1,200 획득",
        chain_gold_3: "골드 2,000 획득",
        chain_zone: "개척의 길",
        chain_zone_1: "지역 6 도달",
        chain_zone_2: "지역 8 도달",
        chain_zone_3: "지역 10 도달",
        chain_master: "달인의 길",
        chain_master_1: "몬스터 80마리 처치",
        chain_master_2: "클릭 피해 1,000",
        chain_master_3: "보스 7마리 처치",
      },
      ach: {
        kills_100: { title: "첫 피", desc: "몬스터 100마리 처치" },
        kills_1000: { title: "사신", desc: "몬스터 1,000마리 처치" },
        kills_10000: { title: "강철의 폭풍", desc: "몬스터 10,000마리 처치" },
        boss_50: { title: "보스 사냥꾼", desc: "보스 50마리 처치" },
        boss_200: { title: "보스 학살자", desc: "보스 200마리 처치" },
        chapter_1: { title: "챕터 파괴자", desc: "챕터 보스 1회 처치" },
        chapter_5: { title: "서사 종료", desc: "챕터 보스 5회 처치" },
        prestige_1: { title: "승천자", desc: "전직 1회" },
        prestige_5: { title: "다시 태어난 노장", desc: "전직 5회" },
        honor_10: { title: "명예로운", desc: "명예 10 획득" },
        honor_50: { title: "귀족", desc: "명예 50 획득" },
        rare_weapon: { title: "무기고", desc: "희귀 무기 획득" },
        epic_weapon: { title: "대장간의 혼", desc: "영웅 무기 획득" },
        rare_relic: { title: "희귀한 발견", desc: "희귀 유물 획득" },
        epic_relic: { title: "영웅의 발견", desc: "영웅 유물 획득" },
        rare_rune: { title: "룬 수집가", desc: "희귀 룬 획득" },
        epic_rune: { title: "룬 현자", desc: "영웅 룬 획득" },
        quests_10: { title: "임무 전문가", desc: "퀘스트 10회 완료" },
        quests_50: { title: "퀘스트 군주", desc: "퀘스트 50회 완료" },
        region_ruins: { title: "잿더미 방랑자", desc: "잿더미 폐허 진입" },
        region_crypt: { title: "묘지 탐험가", desc: "지하 묘지 진입" },
        region_void: { title: "공허의 손길", desc: "공허의 문 진입" },
        skills_50: { title: "지휘관", desc: "스킬 50회 사용" },
        skills_200: { title: "전술가", desc: "스킬 200회 사용" },
      },
      title: {
        monster_scout: "몬스터 정찰병",
        grim_reaper: "사신",
        storm_steel: "강철의 폭풍",
        boss_hunter: "보스 사냥꾼",
        boss_bane: "보스 학살자",
        chapter_breaker: "챕터 파괴자",
        saga_ender: "서사 종료",
        ascended: "승천자",
        reborn_veteran: "다시 태어난 노장",
        honored: "명예로운",
        noble: "귀족",
        arsenal: "무기고",
        master_forge: "대장간의 혼",
        relic_seeker: "유물 사냥꾼",
        artifact_hunter: "유물 사냥꾼",
        rune_collector: "룬 수집가",
        rune_sage: "룬 현자",
        taskmaster: "임무 전문가",
        quest_lord: "퀘스트 군주",
        ash_walker: "잿더미 방랑자",
        crypt_delver: "묘지 탐험가",
        void_touched: "공허의 손길",
        commander: "지휘관",
        tactician: "전술가",
        collector: "수집가",
        weekly_victor: "주간 승자",
      },
      log: {
        notEnoughGold: "골드가 부족합니다.",
        upgradeBought: "구매: {name} x{count} (-{gold}G).",
        boughtRune: "룬 구매: {name}.",
        equippedWeapon: "무기 장착: {name}.",
        equippedRelic: "유물 장착: {name}.",
        unequipWeapon: "무기 해제.",
        unequipRelic: "유물 해제.",
        actionBlocked: "동작 차단: {action}.",
        socketedRune: "룬 장착: {name}.",
        removedRune: "룬 제거: {name}.",
        relicRequired: "유물을 먼저 장착하세요.",
        claimQuest: "퀘스트 완료: {title} ({reward}).",
        questRewardRune: "퀘스트 보상: {name}.",
        questComplete: "퀘스트 완료: {title}",
        weeklyComplete: "주간 퀘스트 완료: {title}",
        chainComplete: "연쇄 퀘스트 완료!",
        eventStart: "이벤트 시작: {name}",
        chapterDefeat: "챕터 보스 처치!",
        regionReached: "지역 도달: {name}",
        inventoryFull: "인벤토리 가득 참.",
        inventoryExpand: "인벤토리 확장: {max}칸.",
        runeFull: "룬 보관함 가득 참.",
        shopRefresh: "룬 상점 새로고침.",
        prestige: "전직: 명예 {amount} 획득.",
        weakHit: "약점 타격!",
        runnerDodge: "돌격이 회피했습니다.",
        achievement: "업적 해금: {title}",
        importFail: "가져오기 실패: JSON 오류.",
        saveCopied: "저장 데이터 복사됨.",
        clickBlocked: "클릭 차단: {target}",
        actionError: "동작 오류. 콘솔을 확인하세요.",
        mercHired: "고용: {name}.",
        mercEquipped: "장착: {name}.",
        mercUnequipped: "해제: {name}.",
        mercLeveled: "강화: {name} +{count} (-{gold}G).",
        mercSlotUnlocked: "용병 슬롯이 해금되었습니다.",
      },
      reward: {
        greedTitle: "탐욕",
        greedDesc: "+3% 골드 획득",
        slayerTitle: "학살자",
        slayerDesc: "보스 피해 +5%",
        focusTitle: "집중",
        focusDesc: "스킬 재사용 대기 -3%",
        sparkTitle: "불꽃",
        sparkDesc: "클릭 피해 +2%",
        engineTitle: "엔진",
        engineDesc: "자동 DPS +2%",
        refreshTitle: "검소함",
        refreshDesc: "상점 새로고침 비용 -10%",
        runeRareTitle: "비전",
        runeRareDesc: "룬 희귀 확률 +2%",
        sellTitle: "중개인",
        sellDesc: "판매가 +10%",
      },
      boss: {
        guardDesc: "6초마다 2.5초간 방어(클릭 피해 -50%).",
        evasionDesc: "클릭 공격 20% 회피.",
        enrageDesc: "HP 30% 이하면 피해 +15%.",
      },
      tutorial: {
        title: "튜토리얼",
        step1: "몬스터를 5번 클릭하세요.",
        step2: "검술 훈련을 1회 구매하세요.",
        step3: "자동 전투 훈련을 1회 구매하세요.",
        step4: "스킬을 1회 사용하세요.",
        step5: "룬 탭을 열고 룬을 구매하세요.",
        moreGold: "골드가 부족하면 몬스터를 더 처치하세요.",
        next: "다음",
        skip: "건너뛰기",
      },
    },
  };
})();
